# This file contains values from Cookiecutter

default_context:
  project_name: "mixpeek"
  project_description: "Package for using the Mixpeek api: file search for your software"
  organization: "mixpeek"
  license: "MIT"
  minimal_python_version: 3.8
  github_name: "mixpeek"
  email: "info@mixpeek.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
